#!/sbin/sh


cat /dev/input/event2 > /dev/keycheck&
sleep 3
kill -9 $!
if [ -s /dev/keycheck ]
then
mount -o remount,rw rootfs /
umount /system
umount /data
umount /cache
umount /mnt/sdcard
rm -r /sdcard
rm -r /not/sdcard
mkdir /sdcard
mkdir /tmp
mount /dev/block/mmcblk0p1 /sdcard
/sbin/recovery &
/sbin/adbd recovery 
fi

if [ -e /cache/recovery/boot ]
then
rm /cache/recovery/boot
mount -o remount,rw rootfs /
umount /system
umount /data
umount /cache
umount /mnt/sdcard
rm -r /sdcard
rm -r /not/sdcard
mkdir /sdcard
mkdir /tmp
mount /dev/block/mmcblk0p1 /sdcard
/sbin/recovery &
/sbin/adbd recovery 
fi

#continue booting

/system/bin/charger
