#!/sbin/sh

# fixing CPU clocks to avoid issues in recovery
echo 998400 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 245000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

echo 0 > /sys/class/android_usb/android0/enable
echo 0FCE > /sys/class/android_usb/android0/idVendor
echo 614F > /sys/class/android_usb/android0/idProduct
echo mass_storage,adb > /sys/class/android_usb/android0/functions
echo 1 > /sys/class/android_usb/android0/enable
stop adbd

# trigger amber LED
echo '255' > /sys/class/leds/lv5219lg:rgb1:blue/brightness
echo '255' > /sys/class/leds/lv5219lg:rgb1:red/brightness
echo '0' > /sys/class/leds/lv5219lg:rgb1:green/brightness
# trigger button-backlight
echo '255' > /sys/class/leds/lv5219lg:sled/brightness
cat /dev/input/event2 > /dev/keycheck&
sleep 3
# trigger amber LED
echo '0' > /sys/class/leds/lv5219lg:rgb1:blue/brightness
echo '0' > /sys/class/leds/lv5219lg:rgb1:red/brightness
echo '0' > /sys/class/leds/lv5219lg:rgb1:green/brightness
# trigger button-backlight
echo '0' > /sys/class/leds/lv5219lg:sled/brightness

kill -9 $!
