#!/sbin/sh

# fixing CPU clocks to avoid issues in recovery
echo 998400 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 245000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

# trigger amber LED
echo '255' > /sys/class/leds/lv5219lg:rgb1:blue/brightness
echo '255' > /sys/class/leds/lv5219lg:rgb1:red/brightness
echo '0' > /sys/class/leds/lv5219lg:rgb1:green/brightness
# trigger button-backlight
echo '255' > /sys/class/leds/lv5219lg:sled/brightness
cat /dev/input/event2 > /dev/keycheck&
sleep 3
# trigger amber LED
echo '0' > /sys/class/leds/lv5219lg:rgb1:blue/brightness
echo '0' > /sys/class/leds/lv5219lg:rgb1:red/brightness
echo '0' > /sys/class/leds/lv5219lg:rgb1:green/brightness
# trigger button-backlight
echo '0' > /sys/class/leds/lv5219lg:sled/brightness

kill -9 $!
if [ -s /dev/keycheck -o -e /cache/recovery/boot ]
then

rm /cache/recovery/boot
mount -o remount,rw rootfs /
umount -l /system
umount -l /data
umount -l /cache
umount -l /mnt/sdcard
rm -r /sdcard
rm -r /not/sdcard
mkdir /sdcard
mkdir /tmp
rm /etc
mkdir /etc
cp /recovery.fstab /etc/recovery.fstab
mount /dev/block/mmcblk0p1 /sdcard
/sbin/recovery &
/sbin/adbd recovery
fi

/system/bin/chargemon

#continue booting

