#!/system/xbin/sh

/system/bin/charger

sleep 2
kill -9 $!


    umount /cache
    umount /sdcard
    umount /cdrom
    umount /data/DxDrm/fuse
    killall -9 DxDrmServerIpc
    insmod /system/kernel/splboot.ko
    sync
    cat /system/kernel/miniloader > /proc/splboot/image
    cat /system/kernel/boot.img > /proc/splboot/boot_img
    echo > /proc/splboot/boot
